runtime: nodejs22
service: jokes-app
handlers:
  - url: /
    static_files: dist/dad-jokes/index.html
    upload: dist/dad-jokes/index.html

  - url: /(.*)
    static_files: dist/dad-jokes/\1
    upload: dist/dad-jokes/(.*)

automatic_scaling:
  target_cpu_utilization: 0.90
  min_instances: 1
  max_instances: 1
